### PR TITLE
Lewinj patch 1

### PR DESCRIPTION
**Pull request by lewinj**
I redone the endplay function so now the only changes are to A_FMU.cpp and A_FMU.h. I don't know why github thinks I entirely replaced then A_FMU.cpp file, but I have verified that other than the added endplay function they are the same.

### CODE REVIEW

**Comment by greenwoodms06** [comment]
Have you tried to put the `delete mFmu` line be after the `Super...` line? If it doesn't matter from your end. move it down there and delete the commented line in `EndPlay`

**Comment by greenwoodms06** [comment]
FYI, if you didn't already know. When you make a pull request, you don't need to make a new one if you need to do more commits. Just make the commits to you branch and they will show up in this pull request.

**Comment by lewinj** [comment]
I didn't know that, and I'm pretty sure it does matter. I'll make those changes.

**Comment by greenwoodms06** [comment]
alright. so for your application everything is good to go on this pull request?

**Comment by lewinj** [comment]
yes

**Comment by greenwoodms06** [comment]
alrighty then. ill accept the merge request and close

**Pull request merged**
